// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2.Data;

#nullable disable

namespace Parcial2.Migrations
{
    [DbContext(typeof(AlfajorContext))]
    [Migration("20230703222249_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("MarcaAlfajores", b =>
                {
                    b.Property<int>("AlfajorsAlfajorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcasMarcaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlfajorsAlfajorID", "MarcasMarcaID");

                    b.HasIndex("MarcasMarcaID");

                    b.ToTable("MarcaAlfajores");
                });

            modelBuilder.Entity("Parcial2.Models.Alfajor", b =>
                {
                    b.Property<int>("AlfajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calorias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAlfajor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlfajorID");

                    b.ToTable("Alfajor");
                });

            modelBuilder.Entity("Parcial2.Models.Marca", b =>
                {
                    b.Property<int>("MarcaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisMarca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MarcaID");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("MarcaAlfajores", b =>
                {
                    b.HasOne("Parcial2.Models.Alfajor", null)
                        .WithMany()
                        .HasForeignKey("AlfajorsAlfajorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcial2.Models.Marca", null)
                        .WithMany()
                        .HasForeignKey("MarcasMarcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
